
import { GameEntry, HieroglyphEntry, SynonymEntry } from './types';

export const GAME_WORDS_LVL1: GameEntry[] = [
  { text: "Haizpea", egoera: "ondo dago" },
  { text: "Halterofilia", egoera: "ondo dago" },
  { text: "Hieroglifikoa", egoera: "ondo dago" },
  { text: "Husadioa", egoera: "gaizki dago" },
  { text: "Hurkoa", egoera: "ondo dago" },
  { text: "Harpa", egoera: "ondo dago" },
  { text: "Hatabala", egoera: "gaizki dago" },
  { text: "Hozbera", egoera: "ondo dago" },
  { text: "Homoplatoa", egoera: "gaizki dago" },
  { text: "Harmaila", egoera: "ondo dago" },
  { text: "Helizea", egoera: "ondo dago" }
];

export const GAME_WORDS_LVL2: GameEntry[] = [
  { text: "Hierarkia", egoera: "ondo dago" },
  { text: "Hautsa", egoera: "ondo dago" },
  { text: "Zihur", egoera: "gaizki dago" },
  { text: "Humorea", egoera: "ondo dago" },
  { text: "Hereserkia", egoera: "gaizki dago" },
  { text: "Uhina", egoera: "ondo dago" },
  { text: "Hautsi", egoera: "ondo dago" },
  { text: "Zehar", egoera: "ondo dago" },
  { text: "Leihoa", egoera: "ondo dago" },
  { text: "Hibernatu", egoera: "ondo dago" },
  { text: "Hestea", egoera: "ondo dago" },
  { text: "antzeman", egoera: "ondo dago" },
  { text: "izutu", egoera: "ondo dago" },
  { text: "hikzi", egoera: "gaizki dago" },
  { text: "ulergaitz", egoera: "ondo dago" },
  { text: "zuspertu", egoera: "gaizki dago" },
  { text: "igorri", egoera: "ondo dago" },
  { text: "seken", egoera: "gaizki dago" },
  { text: "jakiteko grina", egoera: "ondo dago" },
  { text: "are gehiago", egoera: "ondo dago" },
  { text: "leise", egoera: "gaizki dago" },
  { text: "heremu", egoera: "gaizki dago" },
  { text: "hondar", egoera: "ondo dago" },
  { text: "gauzatu", egoera: "ondo dago" },
  { text: "esanahia", egoera: "ondo dago" },
  { text: "lapurtu", egoera: "ondo dago" },
  { text: "ahaztu", egoera: "ondo dago" },
  { text: "aditzera eman", egoera: "ondo dago" },
  { text: "beztela", egoera: "gaizki dago" },
  { text: "nagusitasun", egoera: "ondo dago" },
  { text: "ukitua", egoera: "ondo dago" },
  { text: "oinatz", egoera: "ondo dago" },
  { text: "astarna", egoera: "gaizki dago" },
  { text: "lohitu", egoera: "ondo dago" },
  { text: "jazo", egoera: "ondo dago" },
  { text: "izkanbila", egoera: "gaizki dago" },
];

export const ATSOTITZAK: GameEntry[] = [
  { text: "Azaroa bero, negua gero", egoera: "ondo dago" },
  { text: "Apirilak belar, gauak negar", egoera: "gaizki dago" },
  { text: "Goiz gorri, arrats euri", egoera: "ondo dago" },
  { text: "Eguzki argitan, hautsa izan", egoera: "gaizki dago" },
  { text: "Elur urte, ezkur urte", egoera: "ondo dago" },
  { text: "Goizean oskorri, gauean iturri", egoera: "ondo dago" },
  { text: "Haizea nora, zapiak hara", egoera: "ondo dago" },
  { text: "Otsaileko euri, urteko ongarri", egoera: "ondo dago" },
  { text: "Ilargi berria, sorginen herria", egoera: "gaizki dago" },
  { text: "Otea loretsu, negua elurtsu", egoera: "ondo dago" },
  { text: "Ekaina eder, uda halaber", egoera: "ondo dago" },
  { text: "Abere gaiztoa da gorrotoa.", egoera: "ondo dago" },
  { text: "Ardo gozoak, lau begi eta oinik ez.", egoera: "ondo dago" },
  { text: "Baleki gazteak, baleza zaharrak.", egoera: "ondo dago" },
  { text: "Baleuka eta balitz, elkarren ondoan dabiltz.", egoera: "ondo dago" },
  { text: "Dagoenean bon-bon, ez dagoenean egon.", egoera: "ondo dago" },
  { text: "Ezinak ez du legerik.", egoera: "ondo dago" },
  { text: "Gogoko tokian, aldaparik.", egoera: "gaizki dago" },
  { text: "Hala ez baldin bada, halatsu.", egoera: "ondo dago" },
  { text: "Haritz eroriari, orok egur.", egoera: "ondo dago" },
  { text: "Hil eta lehen, salda bero.", egoera: "gaizki dago" },
  { text: "Hori eta atariko haizea bat.", egoera: "ondo dago" },
  { text: "Jakiteak ez du ogirik jaten.", egoera: "ondo dago" },
  { text: "Kupel txarretik, ardo onik ez.", egoera: "ondo dago" },
  { text: "Lehen hala, orain honela, gero ez jakin nola.", egoera: "ondo dago" },
  { text: "Nori berea, Jaunaren legea, nori berea da gizalegea.", egoera: "ondo dago" },
  { text: "Neke gaberik, ez da konturik.", egoera: "gaizki dago" },
  { text: "Nori berea da zuzenbidea.", egoera: "ondo dago" },
  { text: "Ogi gogorrari hagin zorrotza.", egoera: "ondo dago" },
  { text: "Su gaberik ez da kerik.", egoera: "ondo dago" },
  { text: "Ulertze onari, hitz aski.", egoera: "gaizki dago" },
  { text: "Urak bide eginen du.", egoera: "ondo dago" },
  { text: "Urrutiko intxaurrak hamalau, bertara joan eta lau.", egoera: "ondo dago" },
  { text: "Ustea da jakitea.", egoera: "gaizki dago" },
  { text: "Usteak erdia hutsa eta beste erdia putza.", egoera: "ondo dago" },
  { text: "Zereko zera zertan dela zereko zerarekin.", egoera: "ondo dago" },
  { text: "Zeurea egin artean mantso and mantso; zeurea eginez gero zantzo and zantzo.", egoera: "ondo dago" },
  { text: "Zure izenean eta zure gizenean.", egoera: "gaizki dago" },
];

export const SINONIMOAK: SynonymEntry[] = [
  { hitz: "antzeman", sinonimoak: ["igarri", "nabaritu", "sumatu", "konturatu", "ohartu"] },
  { hitz: "izutu", sinonimoak: ["beldurtu", "ikaratu", "kikildu", "oilotu", "koldartu"] },
  { hitz: "hizki", sinonimoak: ["letra", "igargarri"] },
  { hitz: "ulergaitz", sinonimoak: ["ulertezin", "adiezin", "adigaitz"] },
  { hitz: "suspertu", sinonimoak: ["indarberritu"] },
  { hitz: "igorri", sinonimoak: ["bidali"] },
  { hitz: "zeken", sinonimoak: ["esku-labur", "zikoitz", "doilor", "eskulabur"] },
  { hitz: "jakiteko grina", sinonimoak: ["jakin-min", "jakingura", "jakin-gose", "jakin-nahi"] },
  { hitz: "are gehiago", sinonimoak: ["areago"] },
  { hitz: "leize", sinonimoak: ["kobazulo", "haitzulo"] },
  { hitz: "eremu", sinonimoak: ["alor", "arlo", "esparru", "sail"] },
  { hitz: "hondar", sinonimoak: ["harea", "hondakin"] },
  { hitz: "gauzatu", sinonimoak: ["egin", "burutu"] },
  { hitz: "esanahia", sinonimoak: ["esangura", "adiera", "esankizun"] },
  { hitz: "lapurtu", sinonimoak: ["ostu", "ebatsi"] },
  { hitz: "ahaztu", sinonimoak: ["ahantzi"] },
  { hitz: "aditzera eman", sinonimoak: ["jakinarazi", "ezagutarazi", "adierazi"] },
  { hitz: "bestela", sinonimoak: ["osterantzean", "gainerakoan"] },
  { hitz: "nagusitasun", sinonimoak: ["gailentasun", "gehiagotasun"] },
  { hitz: "ukitua", sinonimoak: ["dei"] },
  { hitz: "oinatz", sinonimoak: ["arrasto", "aztarna"] },
  { hitz: "aztarna", sinonimoak: ["arrasto", "oinatz"] },
  { hitz: "lohitu", sinonimoak: ["zikindu", "likistu", "txerritu", "mantxatu"] },
  { hitz: "jazo", sinonimoak: ["gertatu", "pasatu"] },
  { hitz: "iskanbila", sinonimoak: ["astrapala", "zalaparta", "zarraparra"] },
  { hitz: "ikuzi", sinonimoak: ["garbitu", "txukundu", "xahutu", "araztu"] },
  { hitz: "nabarmendu", sinonimoak: ["nagusitu", "gailendu", "gailurtu"] },
  { hitz: "gizendu", sinonimoak: ["loditu", "guritu", "marduldu", "galantu", "mardotu"] },
  { hitz: "sustraitu", sinonimoak: ["errotu", "zainartu", "erroak bota"] },
  { hitz: "martxan jarri", sinonimoak: ["abiarazi", "abian jarri"] },
  { hitz: "edozenbat", sinonimoak: ["nahi beste", "nahi adina", "gura adina"] },
  { hitz: "miresmen", sinonimoak: ["gurtza"] },
  { hitz: "entzun", sinonimoak: ["aditu"] },
  { hitz: "ulertu", sinonimoak: ["aditu", "jabetu"] },
  { hitz: "ezelango", sinonimoak: ["inola"] },
  { hitz: "zaratatsua", sinonimoak: ["arramatsu", "astrapalatsu"] },
  { hitz: "oztopoa", sinonimoak: ["destorbu", "eragozpen", "traba"] },
  { hitz: "munstro", sinonimoak: ["piztia"] },
  { hitz: "heldu", sinonimoak: ["eutsi", "oratu", "lotu", "iritsi", "ailegatu", "erdutu"] },
  { hitz: "hurko", sinonimoak: ["hurbileko", "aldeko"] },
  { hitz: "kartela", sinonimoak: ["afixa", "idazkun"] },
  { hitz: "arerioa", sinonimoak: ["etsai", "aurkari", "izterbegi"] },
  { hitz: "suertatu", sinonimoak: ["gertatu", "jazo"] },
  { hitz: "hurbildu", sinonimoak: ["hurreratu", "gerturatu"] },
  { hitz: "ekidin", sinonimoak: ["saihestu"] },
  { hitz: "atzaparra", sinonimoak: ["erpe", "atzamar"] },
  { hitz: "seko", sinonimoak: ["guztiz", "zeharo", "total"] }
];

export const HIEROGLYPHS: HieroglyphEntry[] = [
  {
    imageUrl: "ero_00001.webp",
    imageText: "Zure anaia da",
    solution: "Bitxia",
    explanation: ""
  },
  {
    imageUrl: "ero_00002.webp",
    imageText: "Film horretan agertzen da",
    solution: "Apatxea",
    explanation: ""
  },
  {
    imageUrl: "ero_00003.webp",
    imageText: "Ez dakigu nolakoa den",
    solution: "Unibertsoa",
    explanation: ""
  },
  {
    imageUrl: "ero_00004.webp",
    imageText: "Fresko dago",
    solution: "Pomeloa",
    explanation: ""
  },
  {
    imageUrl: "ero_00005.webp",
    imageText: "Arratsalde ederra igaro dugu",
    solution: "Barraketan",
    explanation: ""
  },
  {
    imageUrl: "ero_00006.webp",
    imageText: "Jolas gaitezen",
    solution: "Belarretan",
    explanation: ""
  },
  {
    imageUrl: "ero_00007.webp",
    imageText: "Santiago bidean ikusi nituen",
    solution: "Bi pelegin",
    explanation: ""
  },
  {
    imageUrl: "ero_00008.webp",
    imageText: "Ihesi egiten harrapatu du",
    solution: "Guardiak",
    explanation: ""
  },
  {
    imageUrl: "ero_00009.webp",
    imageText: "Gure herrian eraiki dute",
    solution: "Ospitalea",
    explanation: ""
  },
  {
    imageUrl: "ero_00010.webp",
    imageText: "Izoztu da belardian",
    solution: "Ihintza",
    explanation: ""
  },
  {
    imageUrl: "ero_00011.webp",
    imageText: "Oso gaziak daude",
    solution: "Krispetak",
    explanation: ""
  },
  {
    imageUrl: "ero_00012.webp",
    imageText: "Hegan joan da",
    solution: "Pelikanoa",
    explanation: ""
  },
  {
    imageUrl: "ero_00013.webp",
    imageText: "Zakarrontzira bota dugu",
    solution: "Soberakina",
    explanation: ""
  },
  {
    imageUrl: "ero_00014.webp",
    imageText: "Mesedez ez nazazu",
    solution: "Atzamarkatu",
    explanation: ""
  }
];

export const UI_STRINGS = {
  title: "Begiluze",
  menuSubtitle: "",
  wordsSubtitle: "Sakatu hitzak ondo ala gaizki idatzita dauden jakiteko.",
  proverbsSubtitle: "Sakatu atsotitzak zuzenak ala okerrak diren jakiteko.",
  hieroglyphsSubtitle: "Asmatu eroglifikoaren esanahia.",
  synonymsSubtitle: "Idatzi emandako hitzaren sinonimo bat.",
  playAgain: "Berriro hasi",
  backMenu: "Menura itzuli",
  nextLevel: "Hurrengo zerrenda",
  nextHiero: "Hurrengo eroglifikoa",
  nextSynonym: "Hurrengo hitza",
  correctRemaining: "Zuzenak:",
  wrongRemaining: "Okerrak:",
  correctCount: "Asmatuta:",
  wrongCount: "Huts egin da:",
  remainingCount: "Geratzen dira:",
  score: "Puntuazioa",
  modeWords: "Zuzen idatzita",
  modeProverbs: "Atsotitzak",
  modeHieroglyphs: "Eroglifikoak",
  modeSynonyms: "Sinonimoak",
  modeDaily: "Eguneroko jokoa",
  solution: "Emaitza ikusi",
  hiddenSolution: "Ezkutuko emaitza:",
  possibleSynonyms: "Sinonimo posibleak:",
  timerPrefix: "Denbora amaitu baino lehen idatzi: ",
  timerExpired: "Denbora amaitu da!",
  dictionary: "Hiztegia",
  guessPlaceholder: "Idatzi zure erantzuna...",
  checkButton: "Egiaztatu",
  correctFeedback: "Biba zu! Asmatu duzu!",
  wrongFeedback: "Ez da hori... Saiatu berriro!",
  targetWord: "Hitz hau dugu:",
  isCorrectQuestion: "Ondo idatzita dago?",
  isProverbCorrectQuestion: "Atsotitz zuzena da?",
  ondo: "Ondo",
  gaizki: "Gaizki",
  zuzena: "Zuzena",
  okerra: "Okerra",
  dailyFinished: "Gaurko jokoa amaitu duzu! Bihar arte!",
  nextChallenge: "Hurrengo erronka"
};
